name: staymitra
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sign_in_button: ^4.0.1
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  font_awesome_icon_class: ^0.0.6
  supabase_flutter: ^2.9.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.2.0
  file_picker: ^10.3.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  uuid: ^4.2.1
  video_player: ^2.8.1
  chewie: ^1.7.4
  share_plus: ^7.2.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/Signinwith/

  # Optimize app size
  generate: true
